kind: Service
apiVersion: v1
metadata:
  name: httpbin-service
  namespace: flux-deploy
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
